# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Left <- function(x) {
    .Call(`_mapR_Left`, x)
}

Right <- function(x) {
    .Call(`_mapR_Right`, x)
}

